### PR TITLE
SofaPython3

### PR DESCRIPTION
**Pull request by EulalieCoevoet**

### CODE REVIEW

**Comment by damienmarchal** [comment]
> Nice catch, tu as l'oeil ^^ (merci de regarder btw)
> J'avoue avoir un pris un raccourci parce que j'etais embetee par map... Du coup tu peux peut etre m'expliquer... Pourquoi tu faisais ca? Je ne comprends toujours pas.

Je ne me souvient plus mais en regardant le code je dirais que la liste d'indice retourné par sofa était peut être au format suivant: [[1],[2],[5],[10]] et que je voulais [1,2,5,10]. Donc j'appliquait avec map un fonction lambda pour "transformer" chaque value de la liste fournie par sofa en ne prenant que la première valeur.

**Comment by EulalieCoevoet** [comment]
@damienmarchal I think we should check and merge this PR and continue the work in this direction...

**Comment by damienmarchal** [comment]
I work on it

**Comment by EulalieCoevoet** [comment]
Thanks.

**Comment by damienmarchal** [comment]
Hi, 

The strategy will be the following:
- adds in SofaPython3 the functions that were in SofaPython so old SofaPython scenes are working back, this is a general issue that is of interest for any sofa scene written in python and not only STLIB. 
- for each of these functions, adds a msg_deprecated so users have information they  needs to update there scene (but it is still working) 
- restore/be sure that the feature set of STLIB/stlib and STLIB/splib are  working back
- fix the code in STLIB/stlib and STLIB/splib to remove the deprecation messages emitted
- STLIB/stlib3 and STLIB/splib3 will be only for experiments on top of SofaPython3 and thus will be api-breaking while STLIB/stlib will not be. 

Currently there are pending PR on SofaPython3 waiting to be merged for step1.

**Comment by damienmarchal** [comment]
Here are the news: 
SPLIB now has its own repository (so it is not more in STLIB neither in SofaPython3 (where it was integrated by mistake)). And it  has a sofa-ci style test infrastructure. The repository is now located in: https://github.com/SofaDefrost/SPLIB. 

Now I can work on restoring the STLIB. My first step will be to setup a working tests solutions.

**Comment by EulalieCoevoet** [comment]
Should we merge?

**Pull request merged**
