### PR TITLE
[splib3] Adds features and one fix 

### PR DESCRIPTION
**Pull request by EulalieCoevoet**
In numerics:
- adds to_degrees() function
- fixes createFromEuler (was modifing the parameter rotation, which is by default given by reference in python)

In animation:
- adds endTime option

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi @EulalieCoevoet 

Thanks for the PR.

Could you elaborate a bit more the use case for the endTime parameter in animate. 
It is unclear to me what is its purpose and if its name reflects what it does.

**Comment by EulalieCoevoet** [comment]
It allows to synchronize and loop multiple animations.

**Comment by EulalieCoevoet** [comment]
Let's say you have an animation, with a duration of 2s but you want it to play again or rewind every 4s, you'll set : 
- startTime = 0
- duration = 2
- endTime = 4

@damienmarchal What do you think ?

**Comment by EulalieCoevoet** [comment]
What about `endDelay` with the corresponding new implementation ?

**Comment by EulalieCoevoet** [comment]
@damienmarchal I've made the changes and added an exemple :)

**Comment by EulalieCoevoet** [comment]
@damienmarchal can we merge?

**Comment by damienmarchal** [comment]
@EulalieCoevoet it is ok to me, i just change the code so the parameter is passed as "duration".
If ok to you, you can merge the PR.

**Pull request merged**
